name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
# job for app building with Gradle
  build_test_upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # make executable
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # build and run tests of app
    - name: Build with Gradle
      run: ./gradlew build
      
    # create and upload APK and AAB
    - name: Create APK and AAB
      run: |
         ./gradlew assembleRelease
         ./gradlew bundleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
         name: app-release
         path: ${{ env.apk }}
    - name: Upload AAB Bundle
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: ${{ env.aab }}
