name: PR tests and code lint

# set up launch on pull request to master branch
on:
  pull_request:
    branches: [ "master" ]

# init list of jobs
jobs:
  # job for testing app with Gradle
  run_tests:
    name: Test app
    runs-on: ubuntu-latest

    steps:
      # get repository
      - uses: actions/checkout@v3
      # set java env
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # build and run tests of app
      - name: Test with Gradle
        run: ./gradlew test

  # job for testing app with Gradle
  run_lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      # get repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # set java env
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # run inspect code
      - name: Lint with Gradle
        run: ./gradlew lint

  # job for sending message to telegram project chat about PR
  send_telegram:
    name: Send message to TG chat about commit to master
    # requires .apk build before uploading
    needs: [run_tests, run_lint]
    runs-on: ubuntu-latest
    steps:
      # send to tg chat with bot
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          # add .apk to message
          document: app-release.apk
          message: |
            ${{ github.actor }} created new PR:

            See changes: https://github.com/${{ github.repository }}/pulls

