name: PR tests and code lint

# set up launch on pull request to master branch
on:
  pull_request:
    branches: [ "master" ]

# init list of jobs
jobs:
  # job for testing app with Gradle
  run_tests:
    name: Test app
    runs-on: ubuntu-latest

    steps:
      # get repository
      - uses: actions/checkout@v3
      # set java env
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # build and run tests of app
      - name: Test with Gradle
        run: ./gradlew test

  # job for testing app with Gradle
  run_lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      # get repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # run inspect code
      - name: Lint with Gradle
        run: ./gradlew lint
